export const ADD_TODO="ADD_TODO";
export const DELETE_TODO="DELETE_TODO";
export const DELETE_ALL_TODO="DELETE_ALL_TODO";
export const DELETE_CLICK_TODO="DELETE_CLICK_TODO";
export const DOUBLE_CLICK="DOUBLE_CLICK"
export const EDIT_TODO="EDIT_TODO";

export const WINDOW_CLICK="WINDOW_CLICK";
export const CHECK_BOX="CHECK_BOX";

export const DELETE_SELECT_ITEMS="DELETE_SELECT_ITEMS"